name: deploy-container

on:
  push:
    branches: [master]
    paths:
        - '../../packages/container/**'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
